# Generated by Django 6.0.1 on 2026-02-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Description',
            new_name='P_Description',
        ),
    ]
