# Generated by Django 6.0.1 on 2026-02-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_signupdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdb',
            name='Username',
            field=models.CharField(max_length=100),
        ),
    ]
