# Generated by Django 6.0.1 on 2026-02-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_alter_signupdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdb',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
    ]
