# Generated by Django 6.0.1 on 2026-02-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_signupdb_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Product_Name', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Total_Price', models.FloatField()),
            ],
        ),
    ]
