# Generated by Django 6.0.1 on 2026-02-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Cart Images'),
        ),
    ]
