# Generated by Django 6.0.1 on 2026-03-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_cartdb_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Postcode', models.IntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile', models.IntegerField()),
            ],
        ),
    ]
