# Generated by Django 6.0.1 on 2026-03-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='GrandTotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
